// app/api/simulator/promo-redeem/route.ts
// Redeems a single-use promo code for a credit to the trading balance
// (artifacts/{appId}/users/{uid}/simulator/state.balance — the practice
// money, not the legacy `coins` gating currency).
//
// Codes are generated by app/api/admin/promo-codes/route.ts as
// promo_codes/{CODE} documents. firestore.rules gives the client zero read
// or write access to that collection, so this route and the admin one are
// the only paths that ever touch it.
//
// The whole "single-use" guarantee lives in one Firestore transaction below:
// the code's status is read and flipped to 'used' in the same transaction
// that credits the balance, so two redemption attempts on the same code
// racing each other can only ever have one winner — Firestore's optimistic
// concurrency serializes the losing attempt into a retry that then sees
// status: 'used' and is rejected. A separate "check, then later write" pair
// of calls (the shape the pre-existing welcome-bonus grant used) does not
// have this guarantee.
//
// Per-account limit: one promo redemption ever, tracked as
// users/{uid}.promoCodeRedeemedAt — a protected field firestore.rules
// excludes from client writes, checked in the SAME transaction so a user
// can't redeem two different codes by racing two requests either.

import { NextRequest, NextResponse } from 'next/server';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore, FieldValue } from 'firebase-admin/firestore';
import { moneyAdd, roundMoney } from '@/lib/utils/money';
import { checkPersistentRateLimit } from '@/lib/utils/persistentRateLimit';

// Ensure Firebase Admin is initialized with full credentials
import '@/lib/firebaseAdmin';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

// 5 attempts per minute per uid — generous enough for any real user
// (one attempt is all you need if your code is right), tight enough to
// stop a script guessing random codes and paying for the Firestore reads.
const REDEEM_MAX_ATTEMPTS = 5;
const REDEEM_WINDOW_MS = 60_000;

// Matches app/api/simulator/trade/route.ts's SANE_BALANCE_CAP. Admin SDK
// writes bypass firestore.rules entirely, so every privileged balance
// writer has to re-enforce this cap by hand — see that file's comment.
const SANE_BALANCE_CAP = 100_000_000;

type RedeemFailure =
  | 'INVALID_CODE'
  | 'CODE_ALREADY_USED'
  | 'USER_ALREADY_REDEEMED'
  | 'CODE_DISABLED'
  | 'CODE_EXPIRED'
  | 'BALANCE_CAP';

const FAILURE_RESPONSES: Record<RedeemFailure, { status: number; error: string }> = {
  INVALID_CODE: { status: 404, error: 'That code is not valid.' },
  CODE_ALREADY_USED: { status: 409, error: 'That code has reached its maximum usage limit.' },
  USER_ALREADY_REDEEMED: { status: 409, error: 'You have already redeemed this promo code.' },
  CODE_DISABLED: { status: 409, error: 'That code is no longer active.' },
  CODE_EXPIRED: { status: 410, error: 'That code has expired.' },
  BALANCE_CAP: { status: 400, error: 'This would exceed the maximum allowed balance.' },
};

class RedeemError extends Error {
  constructor(public code: RedeemFailure) {
    super(code);
  }
}

export async function POST(req: NextRequest) {
  try {
    const authHeader = req.headers.get('authorization') || req.headers.get('Authorization');
    if (!authHeader?.startsWith('Bearer ')) {
      return NextResponse.json({ success: false, error: 'Missing or invalid Authorization header' }, { status: 401 });
    }
    const token = authHeader.substring(7).trim();

    const adminAuth = getAuth();
    let decodedToken;
    try {
      decodedToken = await adminAuth.verifyIdToken(token);
    } catch {
      return NextResponse.json({ success: false, error: 'Invalid or expired token' }, { status: 401 });
    }
    const uid = decodedToken.uid;

    // Rate-limit: 5 attempts per uid per minute. Keyed by uid so shared-IP
    // carrier-NAT (common in BD) doesn't punish unrelated users, and a single
    // account can't burn Firestore reads by cycling through guessed codes.
    const allowed = await checkPersistentRateLimit(`promo-redeem:${uid}`, {
      maxRequests: REDEEM_MAX_ATTEMPTS,
      windowMs: REDEEM_WINDOW_MS,
    });
    if (!allowed) {
      return NextResponse.json(
        { success: false, error: 'Too many attempts. Wait a minute and try again.' },
        { status: 429 }
      );
    }

    let body: any;
    try {
      body = await req.json();
    } catch {
      return NextResponse.json({ success: false, error: 'Invalid JSON body' }, { status: 400 });
    }

    const rawCode = body?.code;
    if (typeof rawCode !== 'string' || !rawCode.trim()) {
      return NextResponse.json({ success: false, error: 'Enter a promo code' }, { status: 400 });
    }
    // Same normalization the admin generator produces: uppercase, no
    // whitespace, so pasting-with-spaces or lowercase typing still matches.
    const code = rawCode.trim().toUpperCase().replace(/\s+/g, '');
    if (!/^[A-Z0-9-]{4,32}$/.test(code)) {
      return NextResponse.json({ success: false, error: 'That doesn\'t look like a valid code.' }, { status: 400 });
    }

    const db = getFirestore();
    const appId = process.env.NEXT_PUBLIC_SIMULATOR_APP_ID || 'stocksimulatorbd-dse-v1';
    const userRef = db.doc(`users/${uid}`);
    const promoRef = db.doc(`promo_codes/${code}`);
    const stateRef = db.doc(`artifacts/${appId}/users/${uid}/simulator/state`);

    const result = await db.runTransaction(async (transaction) => {
      const [userSnap, promoSnap, stateSnap] = await Promise.all([
        transaction.get(userRef),
        transaction.get(promoRef),
        transaction.get(stateRef),
      ]);

      if (!promoSnap.exists) {
        throw new RedeemError('INVALID_CODE');
      }

      const promo = promoSnap.data()!;
      if (promo.status === 'disabled') throw new RedeemError('CODE_DISABLED');
      if (promo.status !== 'active') throw new RedeemError('INVALID_CODE');
      if (typeof promo.expiresAt === 'string' && new Date(promo.expiresAt).getTime() < Date.now()) {
        throw new RedeemError('CODE_EXPIRED');
      }

      // Check total usage cap
      const maxUses = typeof promo.maxUses === 'number' && promo.maxUses > 0 ? promo.maxUses : 1;
      const currentUsedCount = typeof promo.usedCount === 'number' ? promo.usedCount : (promo.status === 'used' || promo.redeemed ? 1 : 0);

      if (currentUsedCount >= maxUses || promo.status === 'used') {
        throw new RedeemError('CODE_ALREADY_USED');
      }

      // Check per-user limit
      const maxUsesPerUser = typeof promo.maxUsesPerUser === 'number' && promo.maxUsesPerUser > 0 ? promo.maxUsesPerUser : 1;
      const userData = userSnap.exists ? userSnap.data() : null;
      const userPromoRedemptions = userData?.promoRedemptions || {};
      const userRedemptionCount = typeof userPromoRedemptions[code] === 'number'
        ? userPromoRedemptions[code]
        : (userData?.redeemedPromoCodes && Array.isArray(userData.redeemedPromoCodes) && userData.redeemedPromoCodes.includes(code) ? 1 : 0);

      if (userRedemptionCount >= maxUsesPerUser) {
        throw new RedeemError('USER_ALREADY_REDEEMED');
      }

      const newUsedCount = currentUsedCount + 1;
      const isExhausted = newUsedCount >= maxUses;
      const nowIso = new Date().toISOString();
      const isBossPromo = promo.rewardType === 'boss' || (typeof promo.bossDays === 'number' && promo.bossDays > 0);

      const userEmail = userData?.email || decodedToken.email || null;
      const userName = userData?.name || userData?.displayName || decodedToken.name || null;
      const redemptionId = db.collection('promo_codes').doc().id;

      if (isBossPromo) {
        // ── Boss Tier Promo Redemption ──
        const bossDays = Math.floor(Number(promo.bossDays || 31));
        if (!Number.isFinite(bossDays) || bossDays <= 0 || bossDays > 365) {
          throw new RedeemError('INVALID_CODE');
        }

        const nowMs = Date.now();
        // If user is already active Boss, extend from current expiry; otherwise from now
        const currentUntil =
          userData?.bossUntil && typeof userData.bossUntil === 'number' && userData.bossUntil > nowMs
            ? userData.bossUntil
            : nowMs;
        const newBossUntil = currentUntil + bossDays * 86_400_000;

        const isTrial = bossDays <= 7;
        const planName = isTrial ? `Boss Tier Trial (${bossDays} Days)` : `Promo Code (${bossDays} Days)`;

        const redemptionEntry = {
          id: redemptionId,
          userId: uid,
          userEmail,
          userName,
          rewardType: 'boss',
          bossDays,
          redeemedAt: nowIso,
        };

        // Upgrade user to Boss tier authoritatively
        transaction.set(
          userRef,
          {
            accountTier: 'Boss',
            bossUntil: newBossUntil,
            bossSince: userData?.bossSince || FieldValue.serverTimestamp(),
            lastBossPlan: planName,
            lastPromoRedeemedAt: nowIso,
            promoCodeRedeemedAt: nowIso,
            redeemedPromoCodes: FieldValue.arrayUnion(code),
            [`promoRedemptions.${code}`]: FieldValue.increment(1),
            updatedAt: FieldValue.serverTimestamp(),
          },
          { merge: true }
        );

        // Update promo document
        transaction.update(promoRef, {
          usedCount: newUsedCount,
          status: isExhausted ? 'used' : 'active',
          redeemed: isExhausted,
          redeemedBy: uid,
          redeemedAt: nowIso,
          lastRedeemedAt: nowIso,
          redemptions: FieldValue.arrayUnion(redemptionEntry),
        });

        // Write entry to subcollection for persistent full audit log
        transaction.set(db.doc(`promo_codes/${code}/redemptions/${redemptionId}`), redemptionEntry);

        return {
          rewardType: 'boss' as const,
          bossDays,
          bossUntil: newBossUntil,
        };
      } else {
        // ── Trading Coins Promo Redemption ──
        const amount = promo.amount;
        if (typeof amount !== 'number' || !Number.isFinite(amount) || amount <= 0) {
          throw new RedeemError('INVALID_CODE');
        }

        const currentBalance =
          stateSnap.exists && typeof stateSnap.data()?.balance === 'number' ? stateSnap.data()!.balance : 0;
        const newBalance = roundMoney(moneyAdd(currentBalance, amount));
        if (newBalance > SANE_BALANCE_CAP) {
          throw new RedeemError('BALANCE_CAP');
        }

        if (stateSnap.exists) {
          transaction.update(stateRef, { balance: newBalance });
        } else {
          // Matches app/api/simulator/ensure-state/route.ts zero-state shape
          transaction.set(stateRef, { balance: newBalance, portfolio: [], totalInvested: 0, realizedGainLoss: 0 });
        }

        // Record in coinTransactions ledger
        const txRef = db.collection('coinTransactions').doc();
        transaction.set(txRef, {
          userId: uid,
          amount,
          type: 'promo_code',
          code,
          description: `Promo code ${code} redeemed (+৳${amount.toLocaleString()})`,
          createdAt: FieldValue.serverTimestamp(),
        });

        const redemptionEntry = {
          id: redemptionId,
          userId: uid,
          userEmail,
          userName,
          rewardType: 'coins',
          amount,
          redeemedAt: nowIso,
        };

        // Update promo document
        transaction.update(promoRef, {
          usedCount: newUsedCount,
          status: isExhausted ? 'used' : 'active',
          redeemed: isExhausted,
          redeemedBy: uid,
          redeemedAt: nowIso,
          lastRedeemedAt: nowIso,
          redemptions: FieldValue.arrayUnion(redemptionEntry),
        });

        // Write entry to subcollection for persistent full audit log
        transaction.set(db.doc(`promo_codes/${code}/redemptions/${redemptionId}`), redemptionEntry);

        // Log redemption on user document
        transaction.set(
          userRef,
          {
            lastPromoRedeemedAt: nowIso,
            promoCodeRedeemedAt: nowIso,
            redeemedPromoCodes: FieldValue.arrayUnion(code),
            [`promoRedemptions.${code}`]: FieldValue.increment(1),
            updatedAt: FieldValue.serverTimestamp(),
          },
          { merge: true }
        );

        return {
          rewardType: 'coins' as const,
          amount,
        };
      }
    });

    if (result.rewardType === 'boss') {
      const isTrial = result.bossDays <= 7;
      console.log(`[promo-redeem] 👑 ${uid} redeemed Boss promo ${code} for ${result.bossDays} days (${isTrial ? 'Trial' : 'Full'})`);
      return NextResponse.json({
        success: true,
        rewardType: 'boss',
        bossDays: result.bossDays,
        bossUntil: result.bossUntil,
        isTrial,
        message: isTrial
          ? `👑 Boss Tier Trial activated for ${result.bossDays} days! Enjoy full Risk Radar, PDF statements, and +10% coin bonuses.`
          : `👑 Boss Tier activated for ${result.bossDays} days! Enjoy full Risk Radar, PDF statements, and +10% coin bonuses.`,
      });
    }

    console.log(`[promo-redeem] ✓ ${uid} redeemed Coins promo ${code} for ${result.amount}`);
    return NextResponse.json({
      success: true,
      rewardType: 'coins',
      amount: result.amount,
      message: `৳${result.amount.toLocaleString()} added to your balance!`,
    });
  } catch (err: any) {
    if (err instanceof RedeemError) {
      const { status, error } = FAILURE_RESPONSES[err.code];
      return NextResponse.json({ success: false, error }, { status });
    }
    console.error('[promo-redeem] Failed:', err);
    return NextResponse.json({ success: false, error: 'Failed to redeem code. Please try again.' }, { status: 500 });
  }
}
